# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Vendor name')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone number')),
                ('email_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Email address')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
            },
        ),
    ]
