# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Product name')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RestApp.Vendor', verbose_name='Vendor name')),
            ],
        ),
    ]
